name: quantovaidar
description: "Gerador de Recibos e Orçamentos para Autônomos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.20.2


  uuid: ^4.2.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  pdf: ^3.10.4
  printing: ^5.11.1

  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true