name: faturae
description: "Gerador de Recibos e Orçamentos para Autônomos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  uuid: ^4.2.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # PDF e Impressão
  pdf: ^3.10.4        # Cria o arquivo PDF
  printing: ^5.11.1   # Mostra preview e imprime

  # Compartilhamento
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/